e1 = ['The child liked the chocolate.'] 
e2 = ['She was stopped by the bravest knight.']
e3 = ['Mary baked a cake for his birthday']
e4 = ['She decorated the cake carefully']
e5 = ['Mary wore a dress with polka dots.']

h1 = ['राम ने सीता के लिए फल तोड़ा।']
h2 = ['छोटे बच्चे पाठशाला जल्दी आयेंगे।']
h3 = ['मेहनत का फल मीठा होता है।']
h4 = ['वाह! वह खूबसूरत है।']
h5 = ['पेड़ से पत्ते गिर गए।']